### ISSUE TITLE
Questionable Licensing

### ISSUE THREAD

**Issue by AL-255** [wuxx/TD4-4BIT-CPU#2]
Upon viewing this project files and the associated videos, it's very clear that this entire project is a replication of 4BIT-CPU TD4 presented by Satoshi Watami in his book _CPU no tsukuri kata_.
 At this time, the uploader of this project made zero mention of its origin (In the first video mentioned "by A japanese author", and no more. To my knowledge that not a proper way to address an author in a derivative work.), its original licensing, and selling the kit online. 
All of the deed I mentioned above seemed very questionable: For educational purposes, I "think" it's fine to do so. However, not mentioning or, presumably, not even informing the original author about doing so may violate the spirit of opensource community.

**Comment by wuxx** [comment]
I am very respectful of the works by origin author，as you say, I will add the origin author at the top of this repository。
