### ISSUE TITLE
问一下74hc74这块ic的作用是什么？

### ISSUE THREAD

**Issue by xiezhuojin** [wuxx/TD4-4BIT-CPU#4]
您好，我在b站看了您的视频，这几天clone了这个repo，再看电路图的过程中发现有块74hc74的ic似乎没连到电路中去（本人在电路方面是麻瓜），所以想问一下那块ic的用处是什么？本人在这方面才疏学浅，望谅解与解答。

**Comment by wuxx** [comment]
D触发器，用于FLAG输出，仔细看原理图U1A、U1B

**Comment by xiezhuojin** [comment]
好的，非常感谢！
